# -*- coding: utf-8 -*-
"""app_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HCcdUlC-uQGjfkv31GZK6QoJzBoXJPC1
"""

import streamlit as st
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import re
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import r2_score, mean_squared_error as MSE

# Вспомогательные функции

def extract_numeric(value):
    if pd.isna(value): return None
    match = re.search(r'\d+\.?\d*', str(value))
    return float(match.group()) if match else None

def parse_torque(torque_str):
    if pd.isna(torque_str) or not isinstance(torque_str, str): return None, None
    text = torque_str.lower().replace(',', '').strip()
    torque_value = None
    torque_unit = 'nm'

    t_match = re.search(r'(\d+(?:\.\d+)?)\s*(?:nm|kgm|n·m|kg·m)', text)
    if t_match:
        torque_value = float(t_match.group(1))
        if 'kgm' in t_match.group(0) or 'kg·m' in t_match.group(0):
            torque_value *= 9.80665
    else:
        t_before = re.search(r'(\d+(?:\.\d+)?)(?:@|/|at)', text)
        if t_before: torque_value = float(t_before.group(1))
        if 'kgm' in text or 'kg·m' in text: torque_value *= 9.80665

    rpm_pattern = r'(\d+)-(\d+)\s*rpm|rpm\s*(\d+)-(\d+)|(\d+)\s*rpm|rpm\s*(\d+)'
    rpm_matches = re.findall(rpm_pattern, text)
    rpm_numbers = [int(num) for m in rpm_matches for num in m if num]
    rpm_value = min(rpm_numbers) if rpm_numbers else None

    return (round(torque_value, 2) if torque_value else None, rpm_value)

def add_luxury_feature(df, luxury_list):
    df = df.copy()
    df['brand'] = df['name'].apply(lambda x: str(x).split()[0])
    df['is_luxury'] = df['brand'].apply(lambda x: 1 if x in luxury_list else 0)
    return df

# Интерфейс и загрузка

st.set_page_config(page_title="Car Price Predictor", layout="wide")
st.sidebar.title("Car Price App")

train_up = st.sidebar.file_uploader("1. Загрузите train.csv", type="csv")
test_up = st.sidebar.file_uploader("2. Загрузите test.csv", type="csv")

if train_up and test_up:
    df_train = pd.read_csv(train_up)
    df_test = pd.read_csv(test_up)

    # Препроцессинг
    cols_for_dups = [col for col in df_train.columns if col != 'selling_price']
    df_train.drop_duplicates(subset=cols_for_dups, keep='first', inplace=True)
    df_train = df_train.reset_index(drop=True)

    for df in [df_train, df_test]:
        for col in ['mileage', 'engine', 'max_power']:
            df[col] = df[col].apply(extract_numeric)
        t_data = df['torque'].apply(lambda x: pd.Series(parse_torque(x)))
        df['torque'], df['max_torque_rpm'] = t_data[0], t_data[1]

    target_cols = ['mileage', 'engine', 'max_power', 'seats', 'torque', 'max_torque_rpm']
    medians = {col: df_train[col].median() for col in target_cols}
    for col in target_cols:
        df_train[col] = df_train[col].fillna(medians[col])
        df_test[col] = df_test[col].fillna(medians[col])

    df_train['engine'] = df_train['engine'].astype('int64')
    df_train['seats'] = df_train['seats'].astype('int64')
    df_test['engine'] = df_test['engine'].astype('int64')
    df_test['seats'] = df_test['seats'].astype('int64')

    # Feature engineering
    luxury_list = ['BMW', 'Mercedes-Benz', 'Audi', 'Lexus', 'Jaguar', 'Land', 'Volvo', 'Jeep', 'MG', 'Kia']
    max_year = df_train['year'].max()

    def engineering_full(df):
        df = add_luxury_feature(df, luxury_list)
        df['year_squared'] = df['year'] ** 2
        df['max_power_squared'] = df['max_power'] ** 2
        df['hp_per_liter'] = df['max_power'] / (df['engine'] + 1)
        df['km_per_year'] = df['km_driven'] / (max_year - df['year'] + 1)
        df['is_multi_owner'] = df['owner'].isin(['Third Owner', 'Fourth & Above Owner']).astype(int)
        df['is_high_mileage'] = (df['km_driven'] > 150000).astype(int)
        df['km_driven_log'] = np.log1p(df['km_driven'])
        return df

    df_train = engineering_full(df_train)
    df_test = engineering_full(df_test)
    df_train['selling_price_log'] = np.log1p(df_train['selling_price'])

    # Обучение модели
    y_train_log = df_train['selling_price_log']
    X_train = df_train.drop(columns=['name', 'brand', 'selling_price', 'selling_price_log'])
    X_train_final = pd.get_dummies(X_train, drop_first=True)
    f_names = X_train_final.columns

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_final)

    model = Ridge(alpha=0.1)
    model.fit(X_train_scaled, y_train_log)

    # Меню приложения
    menu = st.sidebar.radio("Раздел", ["📊 EDA", "🤖 Предсказание", "📈 Веса модели"])

    if menu == "📊 EDA":
        st.title("Анализ данных")
        tab1, tab2 = st.tabs(["Корреляция", "Распределения"])
        with tab1:
            fig, ax = plt.subplots(figsize=(10, 8))
            sns.heatmap(df_train.select_dtypes(include=np.number).corr(), annot=True, cmap='coolwarm', fmt=".2f", ax=ax)
            st.pyplot(fig)
        with tab2:
            fig2, ax2 = plt.subplots()
            sns.boxplot(x='fuel', y='selling_price', data=df_train, ax=ax2)
            st.pyplot(fig2)

    elif menu == "🤖 Предсказание":
        st.title("Предсказание стоимости")
        u_name = st.text_input("Марка и модель", "Maruti Swift")
        col1, col2 = st.columns(2)
        with col1:
            u_year = st.slider("Год", 1990, 2024, 2017)
            u_km = st.number_input("Пробег", 0, 500000, 45000)
            u_fuel = st.selectbox("Топливо", ['Diesel', 'Petrol', 'CNG', 'LPG'])
            u_trans = st.selectbox("КПП", ['Manual', 'Automatic'])
        with col2:
            u_pwr = st.number_input("Мощность", 30.0, 600.0, 80.0)
            u_eng = st.number_input("Объем", 600, 6000, 1200)
            u_own = st.selectbox("Владелец", ['First Owner', 'Second Owner', 'Third Owner', 'Fourth & Above Owner'])
            u_seats = st.selectbox("Мест", [4, 5, 6, 7, 8, 9])

        if st.button("Рассчитать цену"):
            # Создание объекта для предсказания
            input_data = pd.DataFrame([[u_name, u_year, u_km, u_fuel, 'Individual', u_trans, u_own, '20 kmpl', u_eng, u_pwr, u_seats, '100Nm@2000rpm']],
                                      columns=['name','year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','seats','torque'])

            # Тот же препроцессинг
            input_data['mileage'] = input_data['mileage'].apply(extract_numeric)
            t_val, r_val = parse_torque(input_data['torque'].iloc[0])
            input_data['torque'], input_data['max_torque_rpm'] = t_val, r_val

            # Инженерия
            input_data = engineering_full(input_data)
            input_data_enc = pd.get_dummies(input_data.drop(columns=['name', 'brand']), drop_first=True)
            input_data_final = input_data_enc.reindex(columns=f_names, fill_value=0)

            # Предсказание
            res_log = model.predict(scaler.transform(input_data_final))
            st.success(f"Рекомендованная цена: {np.expm1(res_log)[0]:,.0f} руб.")

    elif menu == "📈 Веса модели":
        st.title("Влияние признаков")
        coeffs = pd.DataFrame({'Feature': f_names, 'Weight': model.coef_}).sort_values('Weight')
        fig_w, ax_w = plt.subplots(figsize=(10, 12))
        sns.barplot(data=coeffs, x='Weight', y='Feature', ax=ax_w)
        st.pyplot(fig_w)
else:
    st.warning("Загрузите файлы в боковой панели, чтобы начать.")